{
 "title": "Error rates",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate (Events)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", http_route!=\"/metrics\", instance=\"events-api:80\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count{http_route!=\"/metrics\", instance=\"events-api:80\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (Bookings)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", http_route!=\"/metrics\", instance=\"bookings-api:80\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count{http_route!=\"/metrics\", instance=\"bookings-api:80\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (Users)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\", http_route!=\"/metrics\", instance=\"users-api:80\"}[$__rate_interval])) \r\n/ \r\nsum(rate(http_server_request_duration_seconds_count{http_route!=\"/metrics\", instance=\"users-api:80\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}