{
 "title": "Latency",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Booking 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\", instance=\"bookings-api:80\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\", instance=\"events-api:80\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users 0.95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{http_route!=\"/metrics\", instance=\"users-api:80\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}