<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataAccess.Abstract\DataAccess.Abstract.csproj" />
    <ProjectReference Include="..\Events.Service\Events.Service.csproj" />
  </ItemGroup>

</Project>
