<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
	<EnableNETAnalyzers>true</EnableNETAnalyzers>
	<AnalysisMode>All</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bookings.Models\Bookings.Models.csproj" />
    <ProjectReference Include="..\DataAccess.Abstract\DataAccess.Abstract.csproj" />
    <ProjectReference Include="..\Events.Models\Events.Models.csproj" />
  </ItemGroup>

</Project>
